ui:
  image: uifd/ui-for-docker:0.11.0 
  privileged: true
  ports:
    - 9000:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

web:
  build: .
  links:
    - db
  ports:
    - 8069:8069    
  environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USER=odoo
    - DB_PASSWORD=odoo

db:
  image: postgres:9.6.1-alpine  
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
  volumes:
    - /opt/docker/data/db/data:/var/lib/postgresql/data:rw